---
galaxy_info:
  author: "Raghav Palekar"
  company: RemoteSysSupport
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - all
  categories:
  - system
dependencies: []
