---
galaxy_info:
  author: "Raghav Palekar"
  description: "Ansible Role for Firewall - IPTABLES"
  company: "Remote System Support"
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - all
  categories:
  - networking
  - system
dependencies: []
